// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuanLyBaiDoXe_UNETI03_TI17A2HN.Migrations
{
    [DbContext(typeof(QuanLyBaiDoXe_UNETI03_TI17A2HNContext))]
    [Migration("20260922132702_QuanLyBaiDoXe_UNETI03_TI17A2HN")]
    partial class QuanLyBaiDoXe_UNETI03_TI17A2HN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.ChuPhuongTien", b =>
                {
                    b.Property<int>("MaChuPhuongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuPhuongTien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaChuPhuongTien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("ChuPhuongTien");

                    b.HasData(
                        new
                        {
                            MaChuPhuongTien = 1,
                            DiaChi = "Hà Nội",
                            Email = "admin@gmail.com",
                            GioiTinh = true,
                            HoTen = "Quản Trị Viên",
                            MaTaiKhoan = 1,
                            NgayDangKy = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0901234567",
                            TrangThai = true
                        },
                        new
                        {
                            MaChuPhuongTien = 2,
                            DiaChi = "Hà Nội",
                            Email = "huong@gmail.com",
                            GioiTinh = false,
                            HoTen = "Lương Thị Quỳnh Hương",
                            MaTaiKhoan = 2,
                            NgayDangKy = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2005, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0912345678",
                            TrangThai = true
                        },
                        new
                        {
                            MaChuPhuongTien = 3,
                            DiaChi = "Bắc Ninh",
                            Email = "hay@gmail.com",
                            GioiTinh = false,
                            HoTen = "Trịnh Thị Hay",
                            MaTaiKhoan = 3,
                            NgayDangKy = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1998, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0923456789",
                            TrangThai = true
                        },
                        new
                        {
                            MaChuPhuongTien = 4,
                            DiaChi = "Hưng Yên",
                            Email = "diem@gmail.com",
                            GioiTinh = false,
                            HoTen = "Nguyễn Thị Diễm",
                            MaTaiKhoan = 4,
                            NgayDangKy = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2000, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0934567890",
                            TrangThai = true
                        },
                        new
                        {
                            MaChuPhuongTien = 5,
                            DiaChi = "Hà Nam",
                            Email = "giang@gmail.com",
                            GioiTinh = true,
                            HoTen = "Tăng Hoàng Giang",
                            MaTaiKhoan = 5,
                            NgayDangKy = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2002, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0945678901",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.LoaiPhuongTien", b =>
                {
                    b.Property<int>("MaLoaiPhuongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhuongTien"));

                    b.Property<decimal>("DonGiaTheoGio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiPhuongTien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiPhuongTien");

                    b.ToTable("LoaiPhuongTien");

                    b.HasData(
                        new
                        {
                            MaLoaiPhuongTien = 1,
                            DonGiaTheoGio = 5000m,
                            MoTa = "Xe máy số các loại",
                            TenLoaiPhuongTien = "Xe máy số",
                            TrangThai = true
                        },
                        new
                        {
                            MaLoaiPhuongTien = 2,
                            DonGiaTheoGio = 20000m,
                            MoTa = "Ô tô con từ 4 đến 7 chỗ",
                            TenLoaiPhuongTien = "Ô tô 4-7 chỗ",
                            TrangThai = true
                        },
                        new
                        {
                            MaLoaiPhuongTien = 3,
                            DonGiaTheoGio = 4000m,
                            MoTa = "Xe đạp điện và xe máy điện",
                            TenLoaiPhuongTien = "Xe đạp điện / Xe máy điện",
                            TrangThai = true
                        },
                        new
                        {
                            MaLoaiPhuongTien = 4,
                            DonGiaTheoGio = 7000m,
                            MoTa = "Xe tay ga các loại",
                            TenLoaiPhuongTien = "Xe tay ga",
                            TrangThai = true
                        },
                        new
                        {
                            MaLoaiPhuongTien = 5,
                            DonGiaTheoGio = 30000m,
                            MoTa = "Ô tô khách nhỏ và xe bán tải",
                            TenLoaiPhuongTien = "Ô tô trên 7 chỗ",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.PhieuGuiXe", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<decimal>("DonGiaTheoGio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaPhuongTien")
                        .HasColumnType("int");

                    b.Property<int?>("MaViTri")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianDuKienRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianDuKienVao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianRaThucTe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianVaoThucTe")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaPhuongTien");

                    b.HasIndex("MaViTri");

                    b.ToTable("PhieuGuiXe");

                    b.HasData(
                        new
                        {
                            MaPhieu = 1,
                            DonGiaTheoGio = 5000m,
                            MaPhuongTien = 1,
                            MaViTri = 1,
                            NgayDangKy = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThanhTien = 45000m,
                            ThoiGianDuKienRa = new DateTime(2026, 9, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianDuKienVao = new DateTime(2026, 9, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianRaThucTe = new DateTime(2026, 9, 20, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianVaoThucTe = new DateTime(2026, 9, 20, 8, 5, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đã lấy xe"
                        },
                        new
                        {
                            MaPhieu = 2,
                            DonGiaTheoGio = 20000m,
                            MaPhuongTien = 2,
                            MaViTri = 2,
                            NgayDangKy = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianDuKienRa = new DateTime(2026, 9, 22, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianDuKienVao = new DateTime(2026, 9, 22, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianVaoThucTe = new DateTime(2026, 9, 22, 7, 35, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đang gửi"
                        },
                        new
                        {
                            MaPhieu = 3,
                            DonGiaTheoGio = 4000m,
                            MaPhuongTien = 3,
                            MaViTri = 3,
                            NgayDangKy = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianDuKienRa = new DateTime(2026, 9, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianDuKienVao = new DateTime(2026, 9, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Chờ xác nhận"
                        },
                        new
                        {
                            MaPhieu = 4,
                            DonGiaTheoGio = 7000m,
                            MaPhuongTien = 4,
                            MaViTri = 4,
                            NgayDangKy = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianDuKienRa = new DateTime(2026, 9, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianDuKienVao = new DateTime(2026, 9, 22, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianVaoThucTe = new DateTime(2026, 9, 22, 6, 10, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đang gửi"
                        },
                        new
                        {
                            MaPhieu = 5,
                            DonGiaTheoGio = 30000m,
                            MaPhuongTien = 5,
                            MaViTri = 5,
                            NgayDangKy = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThanhTien = 0m,
                            ThoiGianDuKienRa = new DateTime(2026, 9, 21, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianDuKienVao = new DateTime(2026, 9, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đã hủy"
                        });
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.PhuongTien", b =>
                {
                    b.Property<int>("MaPhuongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongTien"));

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaChuPhuongTien")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiPhuongTien")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanHieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaPhuongTien");

                    b.HasIndex("MaChuPhuongTien");

                    b.HasIndex("MaLoaiPhuongTien");

                    b.ToTable("PhuongTien");

                    b.HasData(
                        new
                        {
                            MaPhuongTien = 1,
                            BienSoXe = "29A1-12345",
                            MaChuPhuongTien = 1,
                            MaLoaiPhuongTien = 1,
                            MauSac = "Đỏ",
                            MoTa = "Xe còn mới",
                            NhanHieu = "Honda Wave",
                            TrangThai = true
                        },
                        new
                        {
                            MaPhuongTien = 2,
                            BienSoXe = "30F1-67890",
                            MaChuPhuongTien = 2,
                            MaLoaiPhuongTien = 2,
                            MauSac = "Bạc",
                            MoTa = "Ô tô 5 chỗ",
                            NhanHieu = "Toyota Vios",
                            TrangThai = true
                        },
                        new
                        {
                            MaPhuongTien = 3,
                            BienSoXe = "99M1-55555",
                            MaChuPhuongTien = 3,
                            MaLoaiPhuongTien = 3,
                            MauSac = "Trắng",
                            MoTa = "Xe máy điện",
                            NhanHieu = "VinFast Feliz",
                            TrangThai = true
                        },
                        new
                        {
                            MaPhuongTien = 4,
                            BienSoXe = "89A-11122",
                            MaChuPhuongTien = 4,
                            MaLoaiPhuongTien = 4,
                            MauSac = "Đen",
                            MoTa = "Xe chính chủ",
                            NhanHieu = "Honda SH",
                            TrangThai = true
                        },
                        new
                        {
                            MaPhuongTien = 5,
                            BienSoXe = "90B-33344",
                            MaChuPhuongTien = 5,
                            MaLoaiPhuongTien = 5,
                            MauSac = "Xám",
                            MoTa = "Ô tô 16 chỗ",
                            NhanHieu = "Ford Transit",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = 1,
                            Email = "admin@gmail.com",
                            HoTen = "Quản Trị Viên",
                            MatKhau = "123456",
                            TenDangNhap = "admin",
                            TrangThai = true,
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 2,
                            Email = "huong@gmail.com",
                            HoTen = "Lương Thị Quỳnh Hương",
                            MatKhau = "123456",
                            TenDangNhap = "huong",
                            TrangThai = true,
                            VaiTro = "Khách hàng"
                        },
                        new
                        {
                            MaTaiKhoan = 3,
                            Email = "hay@gmail.com",
                            HoTen = "Trịnh Thị Hay",
                            MatKhau = "123456",
                            TenDangNhap = "hay",
                            TrangThai = true,
                            VaiTro = "Khách hàng"
                        },
                        new
                        {
                            MaTaiKhoan = 4,
                            Email = "diem@gmail.com",
                            HoTen = "Nguyễn Thị Diễm",
                            MatKhau = "123456",
                            TenDangNhap = "diem",
                            TrangThai = true,
                            VaiTro = "Khách hàng"
                        },
                        new
                        {
                            MaTaiKhoan = 5,
                            Email = "giang@gmail.com",
                            HoTen = "Tăng Hoàng Giang",
                            MatKhau = "123456",
                            TenDangNhap = "giang",
                            TrangThai = true,
                            VaiTro = "Khách hàng"
                        });
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.ViTriDoXe", b =>
                {
                    b.Property<int>("MaViTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaViTri"));

                    b.Property<string>("KhuVuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaLoaiPhuongTien")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tang")
                        .HasColumnType("int");

                    b.Property<string>("TenViTri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaViTri");

                    b.HasIndex("MaLoaiPhuongTien");

                    b.ToTable("ViTriDoXe");

                    b.HasData(
                        new
                        {
                            MaViTri = 1,
                            KhuVuc = "Khu A - Xe máy",
                            MaLoaiPhuongTien = 1,
                            MoTa = "Gần cổng vào",
                            Tang = 1,
                            TenViTri = "A1-01",
                            TrangThai = "Còn trống"
                        },
                        new
                        {
                            MaViTri = 2,
                            KhuVuc = "Khu C - Ô tô",
                            MaLoaiPhuongTien = 2,
                            MoTa = "Vị trí rộng rãi",
                            Tang = 1,
                            TenViTri = "C1-01",
                            TrangThai = "Đang sử dụng"
                        },
                        new
                        {
                            MaViTri = 3,
                            KhuVuc = "Khu B - Xe điện",
                            MaLoaiPhuongTien = 3,
                            MoTa = "Có trụ sạc điện",
                            Tang = 1,
                            TenViTri = "B1-01",
                            TrangThai = "Còn trống"
                        },
                        new
                        {
                            MaViTri = 4,
                            KhuVuc = "Khu A - Xe máy",
                            MaLoaiPhuongTien = 4,
                            MoTa = "Cạnh lối đi",
                            Tang = 1,
                            TenViTri = "A1-02",
                            TrangThai = "Đang sử dụng"
                        },
                        new
                        {
                            MaViTri = 5,
                            KhuVuc = "Khu C - Ô tô",
                            MaLoaiPhuongTien = 5,
                            MoTa = "Tầng 2 thoáng mát",
                            Tang = 2,
                            TenViTri = "C2-01",
                            TrangThai = "Còn trống"
                        });
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.ChuPhuongTien", b =>
                {
                    b.HasOne("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("ChuPhuongTien")
                        .HasForeignKey("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.ChuPhuongTien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.PhieuGuiXe", b =>
                {
                    b.HasOne("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.PhuongTien", "PhuongTien")
                        .WithMany("PhieuGuiXes")
                        .HasForeignKey("MaPhuongTien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.ViTriDoXe", "ViTriDoXe")
                        .WithMany("PhieuGuiXes")
                        .HasForeignKey("MaViTri");

                    b.Navigation("PhuongTien");

                    b.Navigation("ViTriDoXe");
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.PhuongTien", b =>
                {
                    b.HasOne("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.ChuPhuongTien", "ChuPhuongTien")
                        .WithMany("PhuongTiens")
                        .HasForeignKey("MaChuPhuongTien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.LoaiPhuongTien", "LoaiPhuongTien")
                        .WithMany("PhuongTiens")
                        .HasForeignKey("MaLoaiPhuongTien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuPhuongTien");

                    b.Navigation("LoaiPhuongTien");
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.ViTriDoXe", b =>
                {
                    b.HasOne("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.LoaiPhuongTien", "LoaiPhuongTien")
                        .WithMany("ViTriDoXes")
                        .HasForeignKey("MaLoaiPhuongTien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhuongTien");
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.ChuPhuongTien", b =>
                {
                    b.Navigation("PhuongTiens");
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.LoaiPhuongTien", b =>
                {
                    b.Navigation("PhuongTiens");

                    b.Navigation("ViTriDoXes");
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.PhuongTien", b =>
                {
                    b.Navigation("PhieuGuiXes");
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("ChuPhuongTien");
                });

            modelBuilder.Entity("QuanLyBaiDoXe_UNETI03_TI17A2HN.Models.ViTriDoXe", b =>
                {
                    b.Navigation("PhieuGuiXes");
                });
#pragma warning restore 612, 618
        }
    }
}
